<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS10yn1b\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS10yn1b/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS10yn1b.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS10yn1b\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS10yn1b\appProdProjectContainer(array(
    'container.build_hash' => 'S10yn1b',
    'container.build_id' => '51a77457',
    'container.build_time' => 1542990128,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerS10yn1b');
